name: Auto Patch Rom

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: testing
        run: |
          echo howdy lmao
          nvm install 24
          node -v
          npm -v
